namespace StrongIdAnalyzer;

[Generator]
public class IdAttributeGenerator : IIncrementalGenerator
{
    // Emitted only from C# 10, where `global using` exists. Below that a consumer writes
    // `using StrongIdAnalyzer;` in the files that tag declarations — the analyzer matches
    // the attributes by metadata name, so nothing else changes.
    const string globalUsingSource =
        """
        // <auto-generated/>
        global using StrongIdAnalyzer;
        """;

    // The attribute declarations are deliberately written in syntax every C# compiler
    // since 2.0 accepts: a block namespace and ordinary constructors, not file-scoped
    // namespaces (C# 10) or primary constructors (C# 12). This source is injected into
    // the consumer's compilation and is parsed at THEIR LangVersion, which for a
    // netstandard2.0 or .NET Framework project defaults to 7.3 — modern syntax here
    // makes such a project fail to compile as soon as the analyzer is referenced, and
    // the language-version switch below cannot rescue it because every form of the
    // declaration has to parse.
    const string sourceHeader =
        """
        // <auto-generated/>
        namespace StrongIdAnalyzer
        {
            using System;
            using System.Diagnostics;
            using System.Diagnostics.CodeAnalysis;

        """;

    const string sourceFooter =
        """
        }
        """;

    const string baseSource =
        """
            /// <summary>
            /// Marks a primitive ID declaration as belonging to a specific domain type so that
            /// the StrongIdAnalyzer can flag crossovers (e.g. a Customer ID being passed where
            /// an Order ID is expected).
            /// </summary>
            [AttributeUsage(
                AttributeTargets.Property |
                AttributeTargets.Field |
                AttributeTargets.Parameter |
                AttributeTargets.ReturnValue,
                Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class IdAttribute : Attribute
            {
                // type is read by the analyzer via metadata, not at runtime
                public IdAttribute(string type)
                {
                }
            }

            /// <summary>
            /// Marks a primitive ID declaration as accepting any one of a set of domain type
            /// tags. Compatible with [Id] when the option sets overlap on at least one entry.
            /// Useful for parameters/properties that legitimately accept multiple Id kinds.
            /// </summary>
            [AttributeUsage(
                AttributeTargets.Property |
                AttributeTargets.Field |
                AttributeTargets.Parameter |
                AttributeTargets.ReturnValue,
                Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class UnionIdAttribute : Attribute
            {
                // types is read by the analyzer via metadata, not at runtime
                public UnionIdAttribute(params string[] types)
                {
                }
            }

            /// <summary>
            /// Marks a generic type parameter as an Id tag source for collection-typed
            /// members of the containing type. <c>WellKnownId&lt;Operation&gt;.Guids</c>,
            /// where <c>Guids</c> is an <c>IEnumerable&lt;Guid&gt;</c>, picks up the element
            /// tag <c>"Operation"</c> at the use site without a per-member attribute —
            /// so LINQ chains and foreach loops over it bind their element variables to
            /// that tag. Scalar members (method returns, properties, parameters) still
            /// need explicit <see cref="IdAttribute"/> / <see cref="UnionIdAttribute"/>.
            /// Open-generic references (T still unsubstituted) produce no tag.
            /// </summary>
            [AttributeUsage(AttributeTargets.GenericParameter, Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class IdTagAttribute : Attribute
            {
            }

            /// <summary>
            /// Tags a property or field declared in a referenced assembly, which cannot carry
            /// <see cref="IdAttribute"/> itself. Read or written through <paramref name="type"/>
            /// or any type derived from it, <paramref name="member"/> carries <paramref name="ids"/>
            /// exactly as if the attribute were on the declaration:
            /// <c>[assembly: ExternalId(typeof(DirectoryObject), nameof(DirectoryObject.Id), "EntraObject")]</c>.
            /// Several attributes for the same member union their ids.
            /// </summary>
            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class ExternalIdAttribute : Attribute
            {
                // All three are read by the analyzer via metadata, not at runtime
                public ExternalIdAttribute(Type type, string member, params string[] ids)
                {
                }
            }

        """;

    // Generic variant — equivalent to [Id(nameof(T))] but enforced by the compiler to
    // reference a real type. Requires C# 11+ (generic attributes).
    const string genericSource =
        """

            /// <summary>
            /// Generic form of <see cref="IdAttribute"/>. <c>[Id&lt;Customer&gt;]</c> is equivalent
            /// to <c>[Id("Customer")]</c> — the analyzer reads the type argument's name as the tag.
            /// </summary>
            [AttributeUsage(
                AttributeTargets.Property |
                AttributeTargets.Field |
                AttributeTargets.Parameter |
                AttributeTargets.ReturnValue,
                Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class IdAttribute<T> : Attribute
            {
            }

            /// <summary>
            /// Generic form of <see cref="UnionIdAttribute"/>. <c>[UnionId&lt;Customer, Order&gt;]</c>
            /// is equivalent to <c>[UnionId("Customer", "Order")]</c>.
            /// </summary>
            [AttributeUsage(
                AttributeTargets.Property |
                AttributeTargets.Field |
                AttributeTargets.Parameter |
                AttributeTargets.ReturnValue,
                Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class UnionIdAttribute<T1, T2> : Attribute
            {
            }

            /// <summary>Three-type generic form of <see cref="UnionIdAttribute"/>.</summary>
            [AttributeUsage(
                AttributeTargets.Property |
                AttributeTargets.Field |
                AttributeTargets.Parameter |
                AttributeTargets.ReturnValue,
                Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class UnionIdAttribute<T1, T2, T3> : Attribute
            {
            }

            /// <summary>Four-type generic form of <see cref="UnionIdAttribute"/>.</summary>
            [AttributeUsage(
                AttributeTargets.Property |
                AttributeTargets.Field |
                AttributeTargets.Parameter |
                AttributeTargets.ReturnValue,
                Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class UnionIdAttribute<T1, T2, T3, T4> : Attribute
            {
            }

            /// <summary>Five-type generic form of <see cref="UnionIdAttribute"/>.</summary>
            [AttributeUsage(
                AttributeTargets.Property |
                AttributeTargets.Field |
                AttributeTargets.Parameter |
                AttributeTargets.ReturnValue,
                Inherited = false)]
            [ExcludeFromCodeCoverage]
            [DebuggerNonUserCode]
            sealed class UnionIdAttribute<T1, T2, T3, T4, T5> : Attribute
            {
            }

        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var languageVersion = context.ParseOptionsProvider.Select((options, _) =>
            options is CSharpParseOptions parse ? parse.LanguageVersion : LanguageVersion.Default);

        // If a referenced assembly already exposes StrongIdAnalyzer.IdAttribute to us
        // (e.g. an upstream project that grants InternalsVisibleTo), skip emitting to
        // avoid CS0436 type-conflict errors. The whole family is skipped on that one
        // probe, so an upstream built with an analyzer that predates ExternalIdAttribute
        // leaves it unavailable downstream — the existing IVT caveat, extended. We must check actual accessibility from
        // the current compilation's assembly — GetTypesByMetadataName returns types
        // from referenced assemblies regardless of accessibility, so an internal-without-IVT
        // match doesn't count.
        var attributeAlreadyVisible = context.CompilationProvider.Select((compilation, _) =>
        {
            var types = compilation.GetTypesByMetadataName("StrongIdAnalyzer.IdAttribute");
            var currentAssembly = compilation.Assembly;
            foreach (var type in types)
            {
                if (SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, currentAssembly))
                {
                    continue;
                }

                if (compilation.IsSymbolAccessibleWithin(type, currentAssembly))
                {
                    return true;
                }
            }

            return false;
        });

        var input = languageVersion.Combine(attributeAlreadyVisible);

        context.RegisterSourceOutput(
            input,
            (productionContext, pair) =>
            {
                var (version, alreadyVisible) = pair;
                if (version >= LanguageVersion.CSharp10)
                {
                    productionContext.AddSource("IdAttributeGlobalUsings.g.cs", globalUsingSource);
                }

                if (alreadyVisible)
                {
                    return;
                }

                var body = version >= LanguageVersion.CSharp11
                    ? baseSource + genericSource
                    : baseSource;
                productionContext.AddSource("IdAttribute.g.cs", sourceHeader + body + sourceFooter);
            });
    }
}
