namespace StrongIdAnalyzer;

[Generator]
public class IdAttributeGenerator : IIncrementalGenerator
{
    const string source = """
        // <auto-generated/>

        global using StrongIdAnalyzer;

        namespace StrongIdAnalyzer;

        using System;
        using System.Diagnostics;
        using System.Diagnostics.CodeAnalysis;

        /// <summary>
        /// Marks a primitive ID declaration as belonging to a specific domain type so that
        /// the StrongIdAnalyzer can flag crossovers (e.g. a Customer ID being passed where
        /// an Order ID is expected).
        /// </summary>
        [AttributeUsage(
            AttributeTargets.Property |
            AttributeTargets.Field |
            AttributeTargets.Parameter |
            AttributeTargets.ReturnValue,
            AllowMultiple = false,
            Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        sealed class IdAttribute(string type) : Attribute
        {
            public string Type { get; } = type;
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context) =>
        context.RegisterPostInitializationOutput(
            _ => _.AddSource("IdAttribute.g.cs", source));
}
