namespace StrongIdAnalyzer;

[Generator]
public class IdAttributeGenerator : IIncrementalGenerator
{
    const string globalUsingSource =
        """
        // <auto-generated/>
        global using StrongIdAnalyzer;
        """;

    const string baseSource =
        """
        // <auto-generated/>
        namespace StrongIdAnalyzer;
        using System;
        using System.Diagnostics;
        using System.Diagnostics.CodeAnalysis;

        /// <summary>
        /// Marks a primitive ID declaration as belonging to a specific domain type so that
        /// the StrongIdAnalyzer can flag crossovers (e.g. a Customer ID being passed where
        /// an Order ID is expected).
        /// </summary>
        [AttributeUsage(
            AttributeTargets.Property |
            AttributeTargets.Field |
            AttributeTargets.Parameter |
            AttributeTargets.ReturnValue,
            Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        // value is read by the analyzer via metadata, not at runtime
        #pragma warning disable CS9113
        sealed class IdAttribute(string type) : Attribute;
        #pragma warning restore CS9113

        /// <summary>
        /// Marks a primitive ID declaration as accepting any one of a set of domain type
        /// tags. Compatible with [Id] when the option sets overlap on at least one entry.
        /// Useful for parameters/properties that legitimately accept multiple Id kinds.
        /// </summary>
        [AttributeUsage(
            AttributeTargets.Property |
            AttributeTargets.Field |
            AttributeTargets.Parameter |
            AttributeTargets.ReturnValue,
            Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        #pragma warning disable CS9113
        sealed class UnionIdAttribute(params string[] types) : Attribute;
        #pragma warning restore CS9113

        /// <summary>
        /// Marks a generic type parameter as an Id tag source for collection-typed
        /// members of the containing type. <c>WellKnownId&lt;Operation&gt;.Guids</c>,
        /// where <c>Guids</c> is an <c>IEnumerable&lt;Guid&gt;</c>, picks up the element
        /// tag <c>"Operation"</c> at the use site without a per-member attribute —
        /// so LINQ chains and foreach loops over it bind their element variables to
        /// that tag. Scalar members (method returns, properties, parameters) still
        /// need explicit <see cref="IdAttribute"/> / <see cref="UnionIdAttribute"/>.
        /// Open-generic references (T still unsubstituted) produce no tag.
        /// </summary>
        [AttributeUsage(AttributeTargets.GenericParameter, Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        sealed class IdTagAttribute : Attribute;
        """;

    // Generic variant — equivalent to [Id(nameof(T))] but enforced by the compiler to
    // reference a real type. Requires C# 11+ (generic attributes).
    const string genericSource =
        """

        /// <summary>
        /// Generic form of <see cref="IdAttribute"/>. <c>[Id&lt;Customer&gt;]</c> is equivalent
        /// to <c>[Id("Customer")]</c> — the analyzer reads the type argument's name as the tag.
        /// </summary>
        [AttributeUsage(
            AttributeTargets.Property |
            AttributeTargets.Field |
            AttributeTargets.Parameter |
            AttributeTargets.ReturnValue,
            Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        sealed class IdAttribute<T> : Attribute;

        /// <summary>
        /// Generic form of <see cref="UnionIdAttribute"/>. <c>[UnionId&lt;Customer, Order&gt;]</c>
        /// is equivalent to <c>[UnionId("Customer", "Order")]</c>.
        /// </summary>
        [AttributeUsage(
            AttributeTargets.Property |
            AttributeTargets.Field |
            AttributeTargets.Parameter |
            AttributeTargets.ReturnValue,
            Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        sealed class UnionIdAttribute<T1, T2> : Attribute;

        /// <summary>Three-type generic form of <see cref="UnionIdAttribute"/>.</summary>
        [AttributeUsage(
            AttributeTargets.Property |
            AttributeTargets.Field |
            AttributeTargets.Parameter |
            AttributeTargets.ReturnValue,
            Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        sealed class UnionIdAttribute<T1, T2, T3> : Attribute;

        /// <summary>Four-type generic form of <see cref="UnionIdAttribute"/>.</summary>
        [AttributeUsage(
            AttributeTargets.Property |
            AttributeTargets.Field |
            AttributeTargets.Parameter |
            AttributeTargets.ReturnValue,
            Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        sealed class UnionIdAttribute<T1, T2, T3, T4> : Attribute;

        /// <summary>Five-type generic form of <see cref="UnionIdAttribute"/>.</summary>
        [AttributeUsage(
            AttributeTargets.Property |
            AttributeTargets.Field |
            AttributeTargets.Parameter |
            AttributeTargets.ReturnValue,
            Inherited = false)]
        [ExcludeFromCodeCoverage]
        [DebuggerNonUserCode]
        sealed class UnionIdAttribute<T1, T2, T3, T4, T5> : Attribute;
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var supportsGenericAttributes = context.ParseOptionsProvider.Select((options, _) =>
            options is CSharpParseOptions { LanguageVersion: >= LanguageVersion.CSharp11 });

        // If a referenced assembly already exposes StrongIdAnalyzer.IdAttribute to us
        // (e.g. an upstream project that grants InternalsVisibleTo), skip emitting to
        // avoid CS0436 type-conflict errors. We must check actual accessibility from
        // the current compilation's assembly — GetTypesByMetadataName returns types
        // from referenced assemblies regardless of accessibility, so an internal-without-IVT
        // match doesn't count.
        var attributeAlreadyVisible = context.CompilationProvider.Select((compilation, _) =>
        {
            var types = compilation.GetTypesByMetadataName("StrongIdAnalyzer.IdAttribute");
            var currentAssembly = compilation.Assembly;
            foreach (var type in types)
            {
                if (SymbolEqualityComparer.Default.Equals(type.ContainingAssembly, currentAssembly))
                {
                    continue;
                }
                if (compilation.IsSymbolAccessibleWithin(type, currentAssembly))
                {
                    return true;
                }
            }
            return false;
        });

        var input = supportsGenericAttributes.Combine(attributeAlreadyVisible);

        context.RegisterSourceOutput(input, (spc, pair) =>
        {
            var (supportsGeneric, alreadyVisible) = pair;
            spc.AddSource("IdAttributeGlobalUsings.g.cs", globalUsingSource);
            if (alreadyVisible)
            {
                return;
            }
            var source = supportsGeneric ? baseSource + genericSource : baseSource;
            spc.AddSource("IdAttribute.g.cs", source);
        });
    }
}
